Update default config file to YAML format
sclorg/mongodb-container pull request #231
Opened 2017-03-13 10:35 UTC by omron93

Update default config file to YAML format which was introduced in MongoDB 2.6.

Few changes:
 - HTTP interface is disable by default from 2.6 (https://docs.mongodb.com/manual/core/security-mongodb-configuration/), so no option about this is necessary 
 - In new format, there are no options "no" prefix (eg noprealloc) -> `MONGODB_NOPREALLOC` have to be negationed

@bparees Please take a look.

Resolves: #197

2017-03-13 10:35 UTC, omron93 commented
[test-openshift]

2017-03-14 09:59 UTC, omron93 commented
[test][test-openshift]

2017-03-14 10:53 UTC, omron93 commented
Fixed problem, that 2.6 has only one storage engine (so mmapv1 options are not separated). Please review...
[test-openshift]

2017-03-15 15:33 UTC, bparees requested changes

2017-03-15 15:33 UTC, bparees commented on 2.6/root/usr/share/container-scripts/mongodb/common.sh
> +fi
you should probably surround this block w/ a check to see if MONGODB_PREALLOC is set and if so, respect that value directly.

And then update the image doc to deprecate MONGODB_NOPREALLOC in preference to MONGODB_PREALLOC

2017-03-15 15:33 UTC, bparees commented on 2.6/test/run
> +    test_config_option MONGODB_QUIET true quiet true
and then add a test for the new env variable here.

2017-03-16 11:14 UTC, omron93 commented on 2.6/root/usr/share/container-scripts/mongodb/common.sh
> +fi
@bparees Thanks.

Changed a way how the default is computed. `MONGODB_PREALLOC` is always preferred. If it is not set, default is get according to `MONGODB_NOPREALLOC`.

2017-03-16 11:15 UTC, omron93 commented
Please review.

2017-03-16 15:59 UTC, bparees requested changes

2017-03-16 15:59 UTC, bparees commented on 2.6/test/run
> +    test_config_option MONGODB_SMALLFILES smallFiles true
should keep the test for NOPREALLOC also since it is technically still supported.

2017-03-16 18:59 UTC, omron93 commented on 2.6/test/run
> +    test_config_option MONGODB_SMALLFILES smallFiles true
@bparees Thanks, testing also `MONGODB_NOPREALLOC` now.

2017-03-16 19:03 UTC, bparees commented
lgtm

2017-03-16 19:05 UTC, omron93 commented
@bparees While inspecting differences among test scripts, I noticed that 2.6 uses deprecated user management functions. (`addUser` renamed to `createUser` and `removeUser` to `dropUser`) -> this is really small change (and no functionality is changed), so I've added it to this PR.

2017-03-16 19:26 UTC, omron93 commented
[test-openshift]

2017-03-20 12:46 UTC, omron93 commented
[test][test-openshift]

2017-03-21 08:56 UTC, omron93 commented
Squashed. [test-openshift]

2017-03-21 09:16 UTC, omron93 commented
Tests are passing. Merging.

@bparees Thanks for review.

2017-03-21 09:17 UTC, merged