Make only admin password mandatory.
sclorg/mongodb-container pull request #232
Opened 2017-03-28 17:15 UTC by omron93

User have to only specify `MONGODB_ADMIN_PASSWORD` and optionally provide settings for user with 'readWrite' role.

Resolves: #32

2017-03-28 17:16 UTC, omron93 commented
[test-openshift]

2017-03-29 05:59 UTC, omron93 commented
[test]

2017-03-29 06:09 UTC, omron93 commented
Changes applied to all versions. [test-openshift]

@bparees Please review.

2017-03-29 14:31 UTC, bparees requested changes
what's the motivation for this change?

edit: nm, i see the issue discussion.

2017-03-29 14:31 UTC, bparees commented on 2.6/root/usr/share/container-scripts/mongodb/init-replset.sh
> +  [[ -v CREATE_USER ]] && mongo_create_user "-u admin -p ${MONGODB_ADMIN_PASSWORD}"
if the admin password is required, why are you not always creating the admin user here?

2017-03-29 14:31 UTC, bparees commented on 2.6/test/run
> +  # postgresql will keep running so we kill it with SIGKILL to make sure
postgresql?

2017-03-30 08:45 UTC, omron93 commented on 2.6/test/run
> +  # postgresql will keep running so we kill it with SIGKILL to make sure
Sorry, it was copied from postgresql-container. Fixed.

2017-03-30 08:47 UTC, omron93 commented on 2.6/root/usr/share/container-scripts/mongodb/init-replset.sh
> +  [[ -v CREATE_USER ]] && mongo_create_user "-u admin -p ${MONGODB_ADMIN_PASSWORD}"
`mongo_create_admin` line creates admin user.

`mongo_create_user` creates "normal" user (passed string contains parameters for `mongo` shell - needs to know how to login)

2017-03-30 08:53 UTC, omron93 commented
> what's the motivation for this change?
edit: nm, i see the issue discussion.

As noted there, other databases also do not require both users [1][2].

In mongodb admin user is not created by default, so it has to be created (otherwise auth have to be disabled and server restarted to allow admin changes). Normal user might not be necessary, also number of env vars needed for running container (for example for testing) is lower :-) 

[1] https://github.com/sclorg/postgresql-container/blob/master/9.5/root/usr/share/container-scripts/postgresql/common.sh#L34
[2] https://github.com/sclorg/mariadb-container/blob/master/10.1/root/usr/share/container-scripts/mysql/validate-variables.sh#L1

[test-openshift]

2017-03-30 13:28 UTC, bparees commented
lgtm

2017-04-03 12:28 UTC, omron93 commented
Squashed and rebased.

2017-04-03 12:33 UTC, omron93 commented
[test-openshift]

2017-04-05 07:28 UTC, omron93 commented
[test][test-openshift]

2017-04-05 08:50 UTC, omron93 commented
LGTM from @bparees and tests are passing. So merging.

2017-04-05 08:50 UTC, merged